# Netlify Configuration
# Place this file in the root directory as netlify.toml

[build]
  command = "npm run build:static"
  publish = "out"

[build.environment]
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://graph.microsoft.com https://login.microsoftonline.com; font-src 'self' data:;"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin","editor"]}

# Environment variables (set in Netlify dashboard)
# NEXT_PUBLIC_AZURE_CLIENT_ID = "your-azure-client-id"
# NEXT_PUBLIC_AZURE_TENANT_ID = "your-azure-tenant-id"  
# NEXT_PUBLIC_REDIRECT_URI = "https://yourdomain.netlify.app"